# 安装 pytorch 和 jupyter-book

In [ ]:
# !conda install pytorch==2.0.0 torchvision==0.15.0 torchaudio==2.0.0 pytorch-cuda=11.8 -c pytorch -c nvidia

In [ ]:
# !pip install jupyter

# 查看Pytorch版本，查看Pytorch是否支持GPU运算。

In [1]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.0.0
True


# 检查NumPy版本

In [2]:
import numpy as np

print(np.__version__)

1.24.3


# numpy.array应用举例

In [3]:
import numpy as np

a = np.array([4, 5, 6, 7])
print(a)
print('*' * 20)
# 多于一个维度
b = np.array([[7, 2], [9, 4]])
print(b)
print('*' * 20)
# 最小维度
c = np.array([91, 72, 63, 74, 5], ndmin=2)
print(c)
print('*' * 20)
# dtype 参数
d = np.array([15, 26, 38], dtype=complex)
print(d)

[4 5 6 7]
********************
[[7 2]
 [9 4]]
********************
[[91 72 63 74  5]]
********************
[15.+0.j 26.+0.j 38.+0.j]


# numpy数据类型应用举例

In [4]:
import numpy as np

# 使用标量类型
dt = np.dtype(np.int32)
print(dt)
print('*' * 10)
# int8, int16, int32, int64 四种数据类型可以使用字符串 'i1', 'i2','i4','i8' 代替
s2 = np.dtype('i4')
print(s2)
print('*' * 10)
# 字节顺序标注
s3 = np.dtype('<i4')
print(s3)
print('*' * 10)
# 首先创建结构化数据类型
s4 = np.dtype([('age', np.int8)])
print(s4)
print('*' * 10)
# 将数据类型应用于ndarray对象
w = np.dtype([('age', np.int8)])
s5 = np.array([(10,), (20,), (30,)], dtype=w)
print(s5)
print('*' * 10)
# 类型字段名可以用于存取实际的 age 列
y = np.dtype([('age', np.int8)])
s6 = np.array([(10,), (20,), (30,)], dtype=y)
print(s6['age'])
print('*' * 10)
student = np.dtype([('name', 'S20'), ('age', 'i1'), ('marks', 'f4')])
print(student)
print('*' * 10)
student = np.dtype([('name', 'S20'), ('age', 'i1'), ('marks', 'f4')])
s8 = np.array([('abc', 21, 50), ('xyz', 18, 75)], dtype=student)
print(s8)

int32
**********
int32
**********
int32
**********
[('age', 'i1')]
**********
[(10,) (20,) (30,)]
**********
[10 20 30]
**********
[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
**********
[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


# numpy.empty创建空数组

In [5]:
import numpy as np

s = np.empty([4, 6], dtype=int)
print(s)

[[-1043707352         451          64           0           0           0]
 [          0           0           0         451  1697998387  1714905955]
 [ 1697789751   808990306   875900984  1714578745   909730613   825779765]
 [  909456695  1664693046   959657266  1701066081  1697669475   962869045]]


# numpy.zeros应用举例说明

In [7]:
import numpy as np

# 默认为浮点数
x = np.zeros(5)
print(x)
# 设置类型为整数
y = np.zeros((5,), dtype=np.int32)
print(y)
# 自定义类型
z = np.zeros((2, 2), dtype=[('x', 'i4'), ('y', 'i4')])
print(z)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


# numpy.ones应用举例说明

In [8]:
import numpy as np

# 默认为浮点数
x = np.ones(5)
print(x)
print('*' * 10)
# 自定义类型
x = np.ones([3, 3], dtype=int)
print(x)

[1. 1. 1. 1. 1.]
**********
[[1 1 1]
 [1 1 1]
 [1 1 1]]


# 将列表转换为ndarray

In [9]:
import numpy as np

x = [4, 5, 6, 10000]
a = np.asarray(x)
print(a)

[    4     5     6 10000]


# 将元组转换为ndarray

In [10]:
import numpy as np

x = (100, 2000, 300000)
a = np.asarray(x)
print(a)

[   100   2000 300000]


# 元组列表转换为ndarray

In [14]:
import numpy as np

x = [(1, 2, 3), (4, 5, 6)]
a = np.asarray(x)
print(a)
print('*' * 10)
# 设置了dtype参数
y = [1, 2, 3]
b = np.asarray(y, dtype=float)
print(b)

[[1 2 3]
 [4 5 6]]
**********
[1. 2. 3.]


# numpy.frombuffer应用实例

In [15]:
import numpy as np

s = b'Hello World'
a = np.frombuffer(s, dtype='S1')
print(a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


# numpy. fromiter应用实例

In [16]:
import numpy as np

# 使用 range 函数创建列表对象
list = range(10)
it = iter(list)
# 使用迭代器创建 ndarray
x = np.fromiter(it, dtype=float)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# numpy加减乘除应用举例

In [17]:
import numpy as np

a = np.arange(0, 27, 3, dtype=np.float_).reshape(3, 3)
print('第一个数组：')
print(a)
print('*' * 20)
print('第二个数组：')
b = np.array([3, 6, 9])
print(b)
print('*' * 20)
print('两个数组相加：')
print(np.add(a, b))
print('*' * 20)
print('两个数组相减：')
print(np.subtract(a, b))
print('*' * 20)
print('两个数组相乘：')
print(np.multiply(a, b))
print('*' * 20)
print('两个数组相除：')
print(np.divide(a, b))

第一个数组：
[[ 0.  3.  6.]
 [ 9. 12. 15.]
 [18. 21. 24.]]
********************
第二个数组：
[3 6 9]
********************
两个数组相加：
[[ 3.  9. 15.]
 [12. 18. 24.]
 [21. 27. 33.]]
********************
两个数组相减：
[[-3. -3. -3.]
 [ 6.  6.  6.]
 [15. 15. 15.]]
********************
两个数组相乘：
[[  0.  18.  54.]
 [ 27.  72. 135.]
 [ 54. 126. 216.]]
********************
两个数组相除：
[[0.         0.5        0.66666667]
 [3.         2.         1.66666667]
 [6.         3.5        2.66666667]]


# numpy.reciprocal()应用举例

In [18]:
import numpy as np

s = np.array([888, 1000, 20, 0.1])
print('原数组是：')
print(s)
print('*' * 20)
print('调用reciprocal函数：')
print(np.reciprocal(s))

原数组是：
[8.88e+02 1.00e+03 2.00e+01 1.00e-01]
********************
调用reciprocal函数：
[1.12612613e-03 1.00000000e-03 5.00000000e-02 1.00000000e+01]


# numpy.power()函数应用举例

In [19]:
import numpy as np

s = np.array([2, 4, 8])
print('原数组是；')
print(s)
print('*' * 20)
print('调用power函数：')
print(np.power(s, 2))
print('*' * 20)
print('power之后数组：')
w = np.array([1, 2, 3])
print(w)
print('*' * 20)
print('再次调用power函数：')
print(np.power(s, w))

原数组是；
[2 4 8]
********************
调用power函数：
[ 4 16 64]
********************
power之后数组：
[1 2 3]
********************
再次调用power函数：
[  2  16 512]


# numpy.mod()应用举例

In [20]:
import numpy as np

s = np.array([3, 6, 9])
w = np.array([2, 4, 8])
print('第一个数组：')
print(s)
print('*' * 20)
print('第二个数组：')
print(w)
print('*' * 20)
print('调用mod()函数：')
print(np.mod(s, w))
print('*' * 20)
print('调用remainder()函数：')
print(np.remainder(s, w))

第一个数组：
[3 6 9]
********************
第二个数组：
[2 4 8]
********************
调用mod()函数：
[1 2 1]
********************
调用remainder()函数：
[1 2 1]


# numpy三角函数应用举例

In [21]:
import numpy as np

a = np.array([0, 30, 45, 60, 90])
print('不同角度的正弦值：')
# 通过乘 pi/180 转化为弧度
print(np.sin(a * np.pi / 180))
print('*' * 20)
print('数组中角度的余弦值：')
print(np.cos(a * np.pi / 180))
print('*' * 20)
print('数组中角度的正切值：')
print(np.tan(a * np.pi / 180))

不同角度的正弦值：
[0.         0.5        0.70710678 0.8660254  1.        ]
********************
数组中角度的余弦值：
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
********************
数组中角度的正切值：
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


# arcsin，arccos，和arctan函数应用举例

In [22]:
import numpy as np

a = np.array([0, 30, 45, 60, 90])
print('含有正弦值的数组：')
sin = np.sin(a * np.pi / 180)
print(sin)
print('*' * 20)
print('计算角度的反正弦，返回值以弧度为单位：')
inv = np.arcsin(sin)
print(inv)
print('*' * 20)
print('通过转化为角度制来检查结果：')
print(np.degrees(inv))
print('*' * 20)
print('arccos 和 arctan 函数行为类似：')
cos = np.cos(a * np.pi / 180)
print(cos)
print('*' * 20)
print('反余弦：')
inv = np.arccos(cos)
print(inv)
print('*' * 20)
print('角度制单位：')
print(np.degrees(inv))
print('*' * 20)
print('tan 函数：')
tan = np.tan(a * np.pi / 180)
print(tan)
print('*' * 20)
print('反正切：')
inv = np.arctan(tan)
print(inv)
print('*' * 20)
print('角度制单位：')
print(np.degrees(inv))

含有正弦值的数组：
[0.         0.5        0.70710678 0.8660254  1.        ]
********************
计算角度的反正弦，返回值以弧度为单位：
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
********************
通过转化为角度制来检查结果：
[ 0. 30. 45. 60. 90.]
********************
arccos 和 arctan 函数行为类似：
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
********************
反余弦：
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
********************
角度制单位：
[ 0. 30. 45. 60. 90.]
********************
tan 函数：
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
********************
反正切：
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
********************
角度制单位：
[ 0. 30. 45. 60. 90.]


# numpy.around()函数应用举例

In [23]:
import numpy as np

a = np.array([100.0, 100.5, 123, 0.876, 76.998])
print('原数组：')
print(a)
print('*' * 20)
print('舍入后：')
print(np.around(a))
print(np.around(a, decimals=1))
print(np.around(a, decimals=-1))

原数组：
[100.    100.5   123.      0.876  76.998]
********************
舍入后：
[100. 100. 123.   1.  77.]
[100.  100.5 123.    0.9  77. ]
[100. 100. 120.   0.  80.]


# numpy.floor()应用举例

In [24]:
import numpy as np

s = np.array([-9999.7, 100333.5, -23340.2, 0.987, 10.88888])
print('提供的数组：')
print(s)
print('*' * 20)
print('修改后的数组：')
print(np.floor(s))

提供的数组：
[-9.999700e+03  1.003335e+05 -2.334020e+04  9.870000e-01  1.088888e+01]
********************
修改后的数组：
[-1.00000e+04  1.00333e+05 -2.33410e+04  0.00000e+00  1.00000e+01]


# numpy.ceil()应用举例

In [25]:
import numpy as np

s = np.array([-100.3, 18.98, -0.49999, 0.563, 10])
print('提供的数组：')
print(s)
print('*' * 20)
print('修改后的数组：')
print(np.ceil(s))

提供的数组：
[-100.3       18.98      -0.49999    0.563     10.     ]
********************
修改后的数组：
[-100.   19.   -0.    1.   10.]


# 绘制简单图形对象